/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CommandPaletteRouteImport } from './routes/command-palette'
import { Route as ElasticTabsRouteImport } from './routes/elastic-tabs'
import { Route as MagneticCursorRouteImport } from './routes/magnetic-cursor'
import { Route as StaggeredRevealRouteImport } from './routes/staggered-reveal'
import { Route as UseDebounceRouteImport } from './routes/use-debounce'
import { Route as UseUndoRouteImport } from './routes/use-undo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandPaletteRoute = CommandPaletteRouteImport.update({
  id: '/command-palette',
  path: '/command-palette',
  getParentRoute: () => rootRouteImport,
} as any)
const ElasticTabsRoute = ElasticTabsRouteImport.update({
  id: '/elastic-tabs',
  path: '/elastic-tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const MagneticCursorRoute = MagneticCursorRouteImport.update({
  id: '/magnetic-cursor',
  path: '/magnetic-cursor',
  getParentRoute: () => rootRouteImport,
} as any)
const StaggeredRevealRoute = StaggeredRevealRouteImport.update({
  id: '/staggered-reveal',
  path: '/staggered-reveal',
  getParentRoute: () => rootRouteImport,
} as any)
const UseDebounceRoute = UseDebounceRouteImport.update({
  id: '/use-debounce',
  path: '/use-debounce',
  getParentRoute: () => rootRouteImport,
} as any)
const UseUndoRoute = UseUndoRouteImport.update({
  id: '/use-undo',
  path: '/use-undo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/command-palette': typeof CommandPaletteRoute
  '/elastic-tabs': typeof ElasticTabsRoute
  '/magnetic-cursor': typeof MagneticCursorRoute
  '/staggered-reveal': typeof StaggeredRevealRoute
  '/use-debounce': typeof UseDebounceRoute
  '/use-undo': typeof UseUndoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/command-palette': typeof CommandPaletteRoute
  '/elastic-tabs': typeof ElasticTabsRoute
  '/magnetic-cursor': typeof MagneticCursorRoute
  '/staggered-reveal': typeof StaggeredRevealRoute
  '/use-debounce': typeof UseDebounceRoute
  '/use-undo': typeof UseUndoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/command-palette': typeof CommandPaletteRoute
  '/elastic-tabs': typeof ElasticTabsRoute
  '/magnetic-cursor': typeof MagneticCursorRoute
  '/staggered-reveal': typeof StaggeredRevealRoute
  '/use-debounce': typeof UseDebounceRoute
  '/use-undo': typeof UseUndoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/command-palette'
    | '/elastic-tabs'
    | '/magnetic-cursor'
    | '/staggered-reveal'
    | '/use-debounce'
    | '/use-undo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/command-palette'
    | '/elastic-tabs'
    | '/magnetic-cursor'
    | '/staggered-reveal'
    | '/use-debounce'
    | '/use-undo'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/command-palette'
    | '/elastic-tabs'
    | '/magnetic-cursor'
    | '/staggered-reveal'
    | '/use-debounce'
    | '/use-undo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommandPaletteRoute: typeof CommandPaletteRoute
  ElasticTabsRoute: typeof ElasticTabsRoute
  MagneticCursorRoute: typeof MagneticCursorRoute
  StaggeredRevealRoute: typeof StaggeredRevealRoute
  UseDebounceRoute: typeof UseDebounceRoute
  UseUndoRoute: typeof UseUndoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-palette': {
      id: '/command-palette'
      path: '/command-palette'
      fullPath: '/command-palette'
      preLoaderRoute: typeof CommandPaletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elastic-tabs': {
      id: '/elastic-tabs'
      path: '/elastic-tabs'
      fullPath: '/elastic-tabs'
      preLoaderRoute: typeof ElasticTabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magnetic-cursor': {
      id: '/magnetic-cursor'
      path: '/magnetic-cursor'
      fullPath: '/magnetic-cursor'
      preLoaderRoute: typeof MagneticCursorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staggered-reveal': {
      id: '/staggered-reveal'
      path: '/staggered-reveal'
      fullPath: '/staggered-reveal'
      preLoaderRoute: typeof StaggeredRevealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-debounce': {
      id: '/use-debounce'
      path: '/use-debounce'
      fullPath: '/use-debounce'
      preLoaderRoute: typeof UseDebounceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-undo': {
      id: '/use-undo'
      path: '/use-undo'
      fullPath: '/use-undo'
      preLoaderRoute: typeof UseUndoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommandPaletteRoute: CommandPaletteRoute,
  ElasticTabsRoute: ElasticTabsRoute,
  MagneticCursorRoute: MagneticCursorRoute,
  StaggeredRevealRoute: StaggeredRevealRoute,
  UseDebounceRoute: UseDebounceRoute,
  UseUndoRoute: UseUndoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
